<!-- generated by claude because i was too lazy lmao -->
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import type { Variant } from '$lib/misc';

	let {
		value = $bindable(0),
		min = 0,
		max = 100,
		step = 1,
		variant = 'primary',
		label = '',
		disabled = false,
		showValue = false,
		format = (v: number) => String(v),
		name = undefined,
		...rest
	}: Omit<HTMLInputAttributes, 'children' | 'value' | 'type'> & {
		value?: number;
		min?: number;
		max?: number;
		step?: number;
		variant?: Variant;
		label?: string;
		disabled?: boolean;
		showValue?: boolean;
		format?: (v: number) => string;
		name?: string;
	} = $props();

	let pct = $derived(max === min ? 0 : ((value - min) / (max - min)) * 100);
</script>

<label class="slider {variant}" class:disabled style="--pct: {pct}%">
	{#if label}<span class="text">{label}</span>{/if}
	<input type="range" bind:value {min} {max} {step} {disabled} {name} {...rest} />
	{#if showValue}<span class="value">{format(value)}</span>{/if}
</label>

<style>
	.slider {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		cursor: pointer;
		user-select: none;
		color: var(--cs-on-surface);
		font-family: var(--font);

		--accent: var(--cs-primary);
		--accent-container: var(--cs-primary-container);
		&.regular {
			--accent: var(--cs-on-surface);
			--accent-container: var(--cs-on-surface-container);
		}
		&.secondary {
			--accent: var(--cs-secondary);
			--accent-container: var(--cs-secondary-container);
		}
		&.tertiary {
			--accent: var(--cs-tertiary);
			--accent-container: var(--cs-tertiary-container);
		}
		&.error {
			--accent: var(--cs-error);
			--accent-container: var(--cs-error-container);
		}
	}
	.slider.disabled {
		cursor: not-allowed;
		opacity: 0.5;
	}

	.value {
		min-width: 3ch;
		text-align: right;
		font-variant-numeric: tabular-nums;
		color: var(--accent);
	}

	input {
		appearance: none;
		-webkit-appearance: none;
		width: 160px;
		height: 24px;
		margin: 0;
		background: transparent;
		cursor: inherit;
		flex: none;
	}

	/* track */
	input::-webkit-slider-runnable-track {
		height: 8px;
		background: linear-gradient(
			to right,
			var(--accent) var(--pct),
			var(--cs-surface-container) var(--pct)
		);
		border: 1px solid var(--cs-outline);
		box-sizing: border-box;
	}
	input::-moz-range-track {
		height: 8px;
		background: var(--cs-surface-container);
		border: 1px solid var(--cs-outline);
		box-sizing: border-box;
	}
	input::-moz-range-progress {
		height: 8px;
		background: var(--accent);
	}

	/* thumb */
	input::-webkit-slider-thumb {
		appearance: none;
		-webkit-appearance: none;
		width: 5px;
		height: 20px;
		margin-top: -7px;
		background: var(--accent);
		outline: none;
		/*border: 1px solid var(--cs-outline);*/
		border: none;
		box-sizing: border-box;
		transition: background 150ms ease;
	}
	input::-moz-range-thumb {
		width: 5px;
		height: 20px;
		background: var(--accent);
		outline: none;
		/*border: 1px solid var(--cs-outline);*/
		border: none;
		border-radius: 0;
		box-sizing: border-box;
		transition: background 150ms ease;
	}

	input:hover:not(:disabled)::-webkit-slider-thumb {
		background: color-mix(in srgb, var(--cs-on-surface) 12%, var(--accent));
	}
	input:hover:not(:disabled)::-moz-range-thumb {
		background: color-mix(in srgb, var(--cs-on-surface) 12%, var(--accent));
	}

	input:focus {
		outline: none;
	}
	input:focus-visible::-webkit-slider-thumb {
		outline: 2px solid var(--accent);
		outline-offset: 2px;
	}
	input:focus-visible::-moz-range-thumb {
		outline: 2px solid var(--accent);
		outline-offset: 2px;
	}

	@media (prefers-reduced-motion: reduce) {
		input::-webkit-slider-thumb,
		input::-moz-range-thumb {
			transition: none;
		}
	}
</style>
